### ISSUE TITLE
Incorrect data types in all sample files

### ISSUE THREAD

**Issue by kdarti** [fNIRS/snirf-samples#11]
Not going to list all, but many items that should be int are float, e.g.

![image](https://github.com/fNIRS/snirf-samples/assets/61238634/e71cc61c-a6b0-4e7a-91cc-49385007a8ef)
![image](https://github.com/fNIRS/snirf-samples/assets/61238634/51c062a3-233a-4634-87d2-a8d2b92438d1)

**Comment by fangq** [comment]
@kdarti, I've fixed various issues related to the format. both sample files now passes the validator. please check it out.

**Comment by kdarti** [comment]
Great, thanks!
