### ISSUE TITLE
SNIRF data licensing question

### ISSUE THREAD

**Issue by rob-luke** [fNIRS/snirf-samples#6]
Hi,

I am writing a SNIRF reader for MNE (https://github.com/mne-tools/mne-python/issues/7057). It seems this repository was created to host example SNIRF data. I can't see a license for this data so I thought I should ask, can I use this repository as test data for my implementation?

Cheers,
Rob

**Comment by fangq** [comment]
hi @rob-luke, the sample files are in the public domain. we previously clarified it in the parent folder ([snirf's LICENSE file](https://github.com/fNIRS/snirf/blob/master/LICENSE.md)). 

I just added a license file in the snirf-samples repo to avoid further confusions. see

https://github.com/fNIRS/snirf-samples/commit/e246efda56957b7023bb64cc948288e47364d1c6

**Comment by rob-luke** [comment]
Thanks
