### ISSUE TITLE
Strings that should be scalars are arrays for multiple items in all sample files

### ISSUE THREAD

**Issue by kdarti** [fNIRS/snirf-samples#9]
snirf spec states that [/nirs/aux/name](https://github.com/fNIRS/snirf/blob/master/snirf_specification.md#nirsiauxjname) strings should be stored as scalars, the same goes for each item under [metadatatags](https://github.com/fNIRS/snirf/blob/master/snirf_specification.md#nirsimetadatatags)
e.g

![image](https://github.com/fNIRS/snirf-samples/assets/61238634/949d5352-1d8a-4d7d-8d43-34785516ea5a)

![image](https://github.com/fNIRS/snirf-samples/assets/61238634/3d063506-443f-4479-82e7-75d0f31c0bfb)

2nd dim always equals number of characters in string.

**Comment by kdarti** [comment]
Actually, it's not only strings, also for other data types there is the same issue.

**Comment by fangq** [comment]
@kdarti, these example files were produced before the SNIRF spec was fully refined and the validator was developed. 

They are [currently produced by](https://github.com/fNIRS/snirf-samples/blob/master/basic/updatesnirffromsrc.m) a general purpose HDF5 reader/writer I wrote for matlab ([EasyH5](https://github.com/NeuroJSON/easyh5)), but EasyH5 handles general data arrays, and is not particularly validating/restricting specific data types in SNIRF fields. The SNIRF-specific data types are supposed to be reinforced in the [jsnirfy toolbox ](https://github.com/NeuroJSON/jsnirfy).

last year, I made the following commits in jsnirfy toolbox to force array-shaped strings to variable-length string (scalar type)

https://github.com/NeuroJSON/jsnirfy/commit/95db007443b58068284f08ff0bd827f94ffaebfd

but I did not rebuild the sample files. I just committed an updated .snirf files [regenerated](https://github.com/fNIRS/snirf-samples/blob/master/basic/updatesnirffromsrc.m) using the latest easyh5 and jsnirfy toolboxes. the string variables are now scalars. please verify.

**Comment by kdarti** [comment]
Thanks, all are scalars now! And thanks for the explanation about jsnirf.

Btw, to avoid making a new issue, I noticed that source and detectorlabels are implemented in this way in the .snirf sample files:
![image](https://github.com/fNIRS/snirf-samples/assets/61238634/03e9e405-0cb0-44e1-8a6c-db9e1c20d7d8)

From my reading of snirf specs this seems incorrect, so probably also a result of making files before spec.

![image](https://github.com/fNIRS/snirf-samples/assets/61238634/ae84a1a0-6ab6-423d-bd64-d62f60407efa)

However, in the jsnirf samples it looks like this:

```
		"sourceLabels": [
				"S1",
				"S2",
				"S3",
				"S4"
			]

```
https://github.com/fNIRS/snirf-samples/blob/3a8505f19a21749bd35f37d8ac988d5e75ca1047/basic/neuro_run01.jnirs#L20805-L20810
